### PR TITLE
Add requirement for java 8 and 9 into CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by iNikem**

### CODE REVIEW

**Comment by iNikem** [comment]
I currently playing with the idea to migrate to java11 or 14, yes. But there are some complications...

**Comment by trask** [comment]
Sounds good. I think I'd prefer Java 11 over Java 14 since Java 11 is an LTS version.

**Comment by iNikem** [comment]
:) Playing devils advocate here: do we plan to buy support? How does LTS or no LTS affect us? But I think there is no actual difference until there are some libraries with minimal supported jdk version higher than 11

**Comment by trask** [comment]
Yeah, what LTS means to me is just critical mass. More developers will have the LTS versions already installed, and won't have to install something special to build this project.

**Comment by jkwatson** [comment]
LTS also means that security patches will be backported, which is a pretty important thing.

**Pull request merged**
