### PR TITLE
Remove unused config

### PR DESCRIPTION
**Pull request by trask**

### CODE REVIEW

**Comment by iNikem** [comment]
How one can specify service/JVM name/identification now?

**Comment by trask** [comment]
This code wasn't being used anyways.

The current way to set `service.name` is a little disjointed though:

For OTLP exporter:

```
export OTEL_RESOURCE_ATTRIBUTES=service.name=shopping
```

For Jaeger exporter:

```
-Dota.exporter.jaeger.service.name=shopping
```

For Zipkin exporter:

```
-Dota.exporter.zipkin.service.name=shopping
```

**Comment by tedsuo** [comment]
Is there no longer any way to set resources?

**Comment by iNikem** [comment]
I believe, (although may be wrong), that service name is set via exporter specific configuration

**Comment by anuraaga** [comment]
I'm currently using this otel env variable

https://github.com/aws-samples/aws-xray-sdk-with-opentelemetry-sample/blob/both-otel-and-xray/frontend/Dockerfile#L15

**Comment by trask** [comment]
Hey @tedsuo, I just created two issues related to your question, do these look like what you are looking for: #703 and #704?

**Comment by tedsuo** [comment]
Thank you @trask! Commenting over there.

**Pull request merged**
