### PR TITLE
Set SpanKind for servlet requests

### PR DESCRIPTION
**Pull request by trask**
I just started testing out the agent with a real exporter(!) and this is first issue I ran into.

### CODE REVIEW

**Comment by trask** [comment]
Unfortunately, there's no test for this yet, but see #89

**Comment by trask** [comment]
Yes, I like that. I think we be moving all of the `startSpan` calls to the decorators as part of #45.

**Comment by prydin** [comment]
Maybe we should address this sooner rather than later? I’m in the process of removing a lot of calls to startSpan in favor of direct calls to the tracer. I’m strongly in favor of Tyler’s suggestion to reincarnate startSpan.

**Comment by prydin** [comment]
...I can take a stab at making Decorator a little smarter if you want. I have some ideas.

**Comment by trask** [comment]
👍 that would be awesome

**Pull request merged**
