### PR TITLE
Use java 11 for compilation

### PR DESCRIPTION
**Pull request by iNikem**
This PR prepares auto-instr to be compiled with 11 by default. This requires several changes.

To support compilation with target bytecode level of java7, all compile tasks have a new `--release` javac argument added. The value of that argument is taken from new gradle project property `release`. By default this property has value of `JavaVersion.VERSION_1_7`, but if project has defined the property `minJavaVersionForTests`, then its value is used. This way all existing instrumentations which has already declared minimal version higher than java 7, will continue to be compiled with that target bytecode level.

This also means that _all classes_ of the instrumentations mentioned above will be compiled with bytecode level 8 or higher. Not only classes residing in `java8` folder. This also means that those folders can be deleted later and their classes merged into common `java` sourceset.

After Gradle implements `https://github.com/gradle/gradle/issues/2510` we can replace `minJavaVersionForTests` with standard `release` option when project needs to override the baseline value.

### CODE REVIEW

**Comment by iNikem** [comment]
@trask do you know how can I change default JVM for CI builds to 11?

**Comment by trask** [comment]
Check out https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/master/.circleci/config.yml#L7

and

https://github.com/DataDog/dd-trace-java-docker-build/blob/master/Dockerfile#L76

I'm planning to move us to Azure Pipelines due to CircleCI cost, so for now maybe we can just override the JAVA_HOME setting in .circleci/config.yml, something like(?)

```
defaults: &defaults
  working_directory: ~/dd-trace-java
  resource_class: xlarge
  docker:
    - image: &default_container datadog/dd-trace-java-docker-build:latest
      environment:
        JAVA_HOME: /usr/local/openjdk-11
```

**Comment by iNikem** [comment]
I have CI build working for `test_7`, but I still need some help with muzzle. It fails with 
```
> Task :instrumentation:jdbc:muzzle-AssertPass-core-jdk FAILED
FAILED MUZZLE VALIDATION: io.opentelemetry.auto.instrumentation.jdbc.ConnectionInstrumentation mismatches:
-- io.opentelemetry.auto.instrumentation.jdbc.JDBCUtils:47 Missing class java.sql.Connection
-- io.opentelemetry.auto.instrumentation.jdbc.JDBCUtils:35 Missing class java.sql.Statement
```

Probably something related to module system. @trask can you help me here?

**Comment by trask** [comment]
Hm, so `java.sql` was moved out of the bootstrap class loader in Java 9 (it caused some issues for me at the time). And muzzle is probably using the bootstrap class loader to determine what classes are safe to assume are always present. Not really sure what the solution to this problem is though.

**Comment by iNikem** [comment]
Muzzle passed! @trask please take a look at my last commit, is it ok?

**Comment by trask** [comment]
Oh, yes, that looks like a good solution 👍

@tylerbenson, what do you think?

**Pull request merged**
