### PR TITLE
Fix sporadic Elasticsearch test failures

### LINKED ISSUE #426: Sporadic test failure (1x): Elasticsearch2SpringTemplateTest
```
BindHttpException[Failed to bind to [33321]]; nested: ChannelException[Failed to bind to: /127.0.0.1:33321]; nested: BindException[Address already in use];
	at org.elasticsearch.http.netty.NettyHttpServerTransport.bindAddress(NettyHttpServerTransport.java:307)
	at org.elasticsearch.http.netty.NettyHttpServerTransport.doStart(NettyHttpServerTransport.java:258)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
	at org.elasticsearch.http.HttpServer.doStart(HttpServer.java:92)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
	at org.elasticsearch.node.Node.start(Node.java:269)
	at springdata.Elasticsearch2SpringTemplateTest.setupSpec(Elasticsearch2SpringTemplateTest.groovy:72)
Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: /127.0.0.1:33321
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
	at org.elasticsearch.http.netty.NettyHttpServerTransport$1.onPortNumber(NettyHttpServerTransport.java:295)
	at org.elasticsearch.common.transport.PortsRange.iterate(PortsRange.java:58)
	at org.elasticsearch.http.netty.NettyHttpServerTransport.bindAddress(NettyHttpServerTransport.java:290)
	... 6 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-auto-instr-java/1090/workflows/71916f9f-bc4c-4d00-a8b4-d370a0f61726/jobs/9037

### PR DESCRIPTION
**Pull request by trask**
Hopefully resolves #426 and #438

### CODE REVIEW

**Comment by iNikem** [comment]
Have you considered instead using https://www.testcontainers.org/modules/elasticsearch/ ?

**Comment by trask** [comment]
No, but I totally agree with going in that direction.

I thought this was going to be an easy "fix" using Spock's `@Retry` annotation until I discovered that `@Retry` only applies to the tests themselves, and not to the setup, which is where these bind exceptions occur.

**Comment by iNikem** [comment]
Your approach is certainly more applicable: the majority of tests which start some server can be solved that way. But it needs at least some documentation. Currently it leaves bad taste in my mouth: "Something is broken here, don't know what exactly, let us just retry".

Another solution, which requires more effort, is to run Elastic in Testcontainer. And probably to run only 1 container for all Elastic related tests, if that is possible. Will speed things up as well.

I am OK with this PR as a short term solution to flakiness, but I think we can do better in a long run.

**Comment by trask** [comment]
👍 good point, added doc to `withRetryOnBindException()`

**Pull request merged**
