### PR TITLE
Make .editorconfig windows friendly

### PR DESCRIPTION
**Pull request by trask**
The current .editorconfig causes Intellij on Windows to change files from CRLF to LF, which then causes the license header check to fail (ugh, don't ask).

### CODE REVIEW

**Comment by tylerbenson** [comment]
Won't this then make the newline be inconsistent?

**Comment by trask** [comment]
Git always changes it to LF on commit.

**Comment by trask** [comment]
Well, it leaves it CRLF in your copy (on Windows), but the committed copy is LF.

**Comment by trask** [comment]
No reason for you to know that unless you use Windows 😄

**Pull request merged**
