### PR TITLE
Better span names for netty

### PR DESCRIPTION
**Pull request by trask**
2 things in this PR:

* Change span name of connect error from `netty.connect` to `CONNECT` (there's no spec for this, but it seems closer to conventions, can re-review in #233)

* Change span kind of connect error from `INTERNAL` to `CLIENT` since these make outgoing calls

### CODE REVIEW

**Comment by safris** [comment]
@trask, is there a reason why you chose to use `CONNECT` rather than `connect`? I reviewed #233, and couldn't find any kind of pattern re capitalization or camel case / snake case.

**Comment by trask** [comment]
I thought that `CONNECT` is more similar to other span names that netty client generates, e.g. `HTTP GET`, `HTTP POST`. Maybe I should change to `HTTP CONNECT`?

**Comment by trask** [comment]
On the other hand, it looks like the netty CONNECT error instrumentation applies to all protocols, and isn't specific to HTTP, so I think leave at just `CONNECT` for now?

**Comment by safris** [comment]
I guess it all comes down to: do we want a global rule for all span names for all integrations? Or do we want the rules to be based on the terminology in the context of individual integrations. Reason I bring this up is because all these names will be shown next to each other in the tracer frontends to the users. Just toying with the idea: if we create a global semantics convention requiring all span names to be lower snake case, then a person would be able to recognize any span name from a glance.

**Comment by trask** [comment]
Can we revisit this idea of a global semantic convention in #233?

**Pull request merged**
