### PR TITLE
Better span names for redis

### PR DESCRIPTION
**Pull request by trask**
3 things going on in this PR:

* Update span names, based on guidance at https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/data-database.md

* Remove "crashing commands" workaround that was specific to DataDog's collector

* Remove `resource.name` attribute, which used to serve similar purpose to span name

### CODE REVIEW

**Comment by safris** [comment]
@trask, is there a reason why you chose to use `SET` rather than `set`? This question is similar to [this](https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/247#issuecomment-601004610).

**Comment by trask** [comment]
We're just capturing the Redis command name (not explicitly uppercasing it). Redis uses uppercase for command names, e.g. https://redis.io/commands/set.

**Comment by safris** [comment]
Reiterating [what I said here](https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/247#issuecomment-601269527), what if we alternatively...
>  create a global semantics convention requiring all span names to be lower snake case, then a person would be able to recognize any span name from a glance.

**Comment by trask** [comment]
Can we revisit this idea of a global semantic convention in #233?

**Pull request merged**
