### PR TITLE
Auto and Contrib sharing common functionality #WIP

### PR DESCRIPTION
**Pull request by kbrockhoff**
Here is a full implementation of the base functionality for tracing, metrics and correlation context which would be shared across all instrumentation. Specific auto and contrib libraries will follow later.

Note that I named stuff correlation context even though the version of the API currently be used still calls it DistributedContext.

The biggest gap I found so far is how will an application specify what values should be added to the correlation context?

**Design Overview**

The main objective is to have all functionality for tracing, metrics and correlation context handled in one place in an integrated way. The API is the two interfaces 'SpanDecorator' and 'SpanScope'.

A 'SpanScope" implementation functions as a DTO that holds the current span, correlation context and scope. If a span switches threads this one object can be propagated and nothing else is needed. It also contains behavior including implementation of the 'Closeable' interface so it can be used by try-with-resources. Once a 'SpanScope' has been created on span start, all other client actions to record telemetry are done through it.

A span is initiated by calling one of the two methods on 'SpanDecorator'. For most use cases, 'callWithTelemetry' should be used. This is a GoF template method. If behavior other than the default implemented by this method is needed then 'startSpan' should be called to create the 'SpanScope' and then the calling code has to handle everything after that.

The default behavior of 'callWithTelemetry' is:

```java  
  public P callWithTelemetry(String spanName, C carrier, Q inbound, Callable<P> callable)
      throws Exception {
    try (SpanScope<Q, P> scope = startSpan(spanName, carrier, inbound)) {
      P response = null;
      try {
        scope.onMessageSent(inbound);
        response = callable.call();
        scope.onMessageReceived(response);
        scope.onSuccess(response);
        addResultSpanAttributes(scope.getSpan(), null, response);
        return response;
      } catch (Throwable throwable) {
        scope.onError(throwable, response);
        addResultSpanAttributes(scope.getSpan(), throwable, response);
        throw throwable;
      }
    }
  }
```

### CODE REVIEW

**Comment by jkwatson** [comment]
I don't see an example in here of it being used in auto-instrumentation, as well as an example being used in manual instrumentation. I think that would be very helpful in evaluating the proposal.

**Comment by trask** [comment]
Linking to #45

**Comment by tylerbenson** [comment]
See #195 for my take on it...

**Comment by trask** [comment]
Closing in favor of typed spans approach in #195.

Thanks @kbrockhoff for offering up the first option and getting everyone going on this!

**Pull request closed without merging**
