### PR TITLE
Separate out core instrumentation for AWS SDK to allow manual setup o…

### PR DESCRIPTION
**Pull request by anuraaga**
…f instrumentation.

Related: #45 

@trask Created this WIP PR exloring separating out the core instrumentation of AWS SDK so it can be used directly by users without the agent. Let me know if this is the direction you had in mind.

I haven't dug into the testing story yet, interestingly in this case, which may not apply for other instrumentation, the manual instrumentation misses out on the feature of being able to propagate context to Netty instrumentation (agent is doing quite an invasive AOP to enable it), so the agent and non-agent would need different test cases anyways.

Let me know if you have any thoughts!

/cc @shengxil

### CODE REVIEW

**Comment by anuraaga** [comment]
I have added a simpler test runner for manual instrumentation tests (doesn't do any agenting). In the end, there is quite a bit of duplication in the test code, but it doesn't seem so bad. An idea is to accompany any e.g. `aws-sdk-2.2-core` module with `aws-sdk-2.2-testing` module with shared testing code, it's quite a bit of tooling though and depending on the instrumentation, may result in very little sharing.

I can't reproduce the build failure locally ><

**Comment by trask** [comment]
Hey @anuraaga, it looks like the test failure is due to a file missing in your commit: `InstrumentationTestRunner.java`

**Comment by anuraaga** [comment]
Ugh, sorry about that!

**Comment by trask** [comment]
Hi @anuraaga, for the remaining build failures:

* `muzzle` - see my suggestion above https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/421#discussion_r428413743
* `test_11` - add `io.opentelemetry.auto.test.InstrumentationTestRunner` to `excludedClassesCoverage` in `testing.gradle` (you'll see `io.opentelemetry.auto.test.AgentTestRunner` is there already)
* `check` - run `./gradlew :testing:codenarcMain` locally and open `testing/build/reports/codenarc/main.html` in your browser to see the issues (you can see the one from the CI run here: https://9052-210933087-gh.circle-artifacts.com/0/reports/testing/codenarc/main.html)

**Comment by anuraaga** [comment]
Thanks for all these hints! For muzzle, unfortunately GitHub isn't recognizing that I did apply the change to the PR. Most of the muzzles started passing but now it gives `Instrumentation unexpectedly passed Muzzle validation`. Any idea what that might be about? Not sure what muzzle is doing yet...

**Comment by anuraaga** [comment]
Was able to get the test to pass by updating the `muzzle` block, but I'm not sure what the implication of this is...

**Comment by anuraaga** [comment]
Think this is finally ready for a look thanks for the patience

**Comment by iNikem** [comment]
I am not sure about code structure here. Having `instrumentation` and `instrumentation-core` as separate top level aggregates bothers me. I would very much prefer to have all code related to one library to be close together. Obvious way would be to have `aws-sdk-2.2-auto` and `aws-sdk-2.2-manual`, but I don't like it neither. What about `aws-sdk-2.2` having code for manual integration and `aws-sdk-2.2-auto` for agent-based auto instrumentation?

@trask @tylerbenson @jkwatson what do you think?

**Comment by anuraaga** [comment]
I definitely agree with that structure / naming and would prefer something like 

```
instrumentation/
  aws-sdk-2.2/
    aws-sdk-2.2
    aws-sdk-2.2-auto
  ...
```

One reason I didn't do that in this PR is it looks like there would be a pretty big refactoring of the Gradle config where currently `instrumentation` configures all its subprojects with everything needed to build into the agent as auto instrumentation, so putting other projects in that folder currently wouldn't work well. Didn't want to tackle such a big change in this PR but let me know if it'd be better.

**Comment by iNikem** [comment]
You are correct regarding Gradle scripts. Can you please add a TODO into README file of this new module? That it should be moved closer to "auto" module whenever build system supports it.

**Comment by anuraaga** [comment]
Yup added it

**Pull request merged**
